version: '3.8'
services:
  db:
    image: postgres:16.0-alpine3.17
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  shelters:
    build: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    command: >
      sh -c "sleep 10 &&
            alembic stamp head &&
            alembic revision --autogenerate -m 'Initial migration' &&
            alembic upgrade head &&
            python -m uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
      - ./certs:/app/certs
    depends_on:
      db:
        condition: service_healthy
